# Generated by Django 2.0.4 on 2018-04-13 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0002_calculatescoremodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_date', models.DateField()),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SubmitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('filename', models.CharField(max_length=50)),
                ('submit_timestamp', models.DateTimeField()),
                ('score_date_start', models.DateField()),
                ('score_date_end', models.DateField()),
                ('score_avg', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='CalculateScoreModel',
        ),
        migrations.DeleteModel(
            name='SubmitFileModel',
        ),
        migrations.AddField(
            model_name='scoremodel',
            name='submit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.SubmitModel'),
        ),
    ]
