# Generated by Django 2.0.4 on 2018-04-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0003_auto_20180413_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitmodel',
            name='for_score_simulation',
            field=models.BooleanField(default=False),
        ),
    ]
