# Generated by Django 2.0.4 on 2018-04-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0005_auto_20180423_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitmodel',
            name='avg_bj_o3_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submitmodel',
            name='avg_bj_pm10_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submitmodel',
            name='avg_bj_pm25_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submitmodel',
            name='avg_ld_pm10_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submitmodel',
            name='avg_ld_pm25_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
